/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 */

rootProject.name = "Ollama"
include("Ollama")
include("BetterFuture")
include("RequestError")
include("RequestError")
include("ResponseError")
include("TrustAllCertificates")
include("BetterFuture")
include("CoroutineError")
include("App")
include("org.json:json:20140107")