/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ollama;


public class App {
        public static void main(String[] args) throws ResponseError {
        try {
            Ollama AI =Ollama.loadDefaultHost();
            OllamaMessageList messages = new OllamaMessageList();
            messages.addMessage(new OllamaMessage("hello what can you do", OllamaMessage.USER));
            IterableFuture<OllamaMessage> message = AI.chat("llama3",messages ,true, null, null, null);
            for (OllamaMessage ollamaMessage : message) {
                
            }
        } catch (RequestError | CoroutineError | Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        }
    }

