/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ollama;

import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONObject;

public class App {
        public static void main(String[] args) {
        try {
            Ollama AI = new Ollama("https://dnjrepair.com:7007");
            OllamaMessageList messageList = new OllamaMessageList();
            messageList.addMessage(new ollama.OllamaMessage("Hello", OllamaMessage.USER, false));
            // OllamaMessage json = AI.chat("llama3", , false, null, null, null); // other
            System.out.println(json.toString());
        } catch (RequestError | CoroutineError | Exception | ResponseError e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        }
    }

