/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ollama;


public class App {
        public static void main(String[] args) throws ResponseError {
            System.out.println("Ollama API Tool is ready");
    }
    public static void test
}

